site_name: ducknx
site_description: Download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap
repo_url: https://github.com/gboeing/osmnx

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            members_order: source

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - User Reference: user-reference.md
  - Internals Reference: internals-reference.md
  - Further Reading: further-reading.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
